### Numpy arrays essentially come in two flavours : Vectors and Matrices.
### Vectors are strictly 1-d arrays and matrices are 2-d(but you  should note a matrix can still have only one row or on column).

## NumPy Arrays:

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat) # Two-dimensional array 3rows are 3 columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#Most common way of creating a numpy array is using np.arange() similar to python's range function
np.arange(0,11,2) #start and end and stepsize(Odd or Even)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
#To get the array of all zeros use np.zeros()
np.zeros(3)

array([0., 0., 0.])

In [18]:
# Parse tuple of the zeros you want
np.zeros((2,3)) #(Rows,Columns)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#Arrays of just ones use np.ones()
np.ones(4) #1-d array

array([1., 1., 1., 1.])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
#np.linspace() -- start,stop,evenly spaced points
np.linspace(0,5,100) #It's1-d dimensional

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

### Creating an Identity Matrix:

In [26]:
np.eye(4) #Takes only a single digit as an argument

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Create an array of random numbers 

In [31]:
np.random.rand(5) #Creates a random sample of uniform distribution from 0 to 1

array([0.24556375, 0.91931647, 0.65893004, 0.79673052, 0.85896126])

In [34]:
np.random.rand(5,5) #Don't use tuples

array([[0.24442743, 0.03881861, 0.32125582, 0.85053845, 0.94102568],
       [0.41634355, 0.28496062, 0.17787359, 0.12847416, 0.60290155],
       [0.67898605, 0.59884213, 0.50393308, 0.18328336, 0.48465417],
       [0.00724585, 0.95336827, 0.64126105, 0.01255344, 0.41300138],
       [0.89870582, 0.71424572, 0.72341534, 0.20300409, 0.52436415]])

In [38]:
# To get the random numbers from the standard normal distribution or Gaussian centred around 0
np.random.randn(2)

array([-0.54130448, -1.13862056])

In [40]:
# For 2-d:
np.random.randn(2,4)

array([[ 1.65333175,  1.16405953,  0.80827429, -1.02812325],
       [ 0.63973491, -0.15810957, -0.03224136,  0.64342545]])

In [43]:
# np.random.randint() --return integers from low to high number
np.random.randint(1,100,10) #(low,high,size) --Lowest inclusive and highest exclusive means 1 can be selected but 100 never

array([43, 28, 75, 90, 23, 33, 87, 10, 36, 41])

#### Methods of arrays

In [44]:
arr = np.arange(25)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
ranarr = np.random.randint(0,50,10)

In [47]:
ranarr

array([ 2, 15, 30,  3, 23, 26, 29, 35, 44, 11])

In [51]:
#reshape array
arr.reshape(5,5) #No of rows * no of columns = Actual elements in an array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Find Min, Max and Index of an array

In [52]:
ranarr

array([ 2, 15, 30,  3, 23, 26, 29, 35, 44, 11])

In [53]:
ranarr.max()

44

In [54]:
ranarr.min()

2

In [55]:
ranarr.argmax() #Returns the index value of the max number

8

In [56]:
ranarr.argmin() #Returns the index value of the min number

0

In [57]:
## Shape of vector:
arr.shape

(25,)

In [58]:
arr = arr.reshape(5,5)

In [59]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr.shape

(5, 5)

In [61]:
##Datatype we have in array:
arr.dtype

dtype('int32')

In [62]:
from numpy.random import randint

In [64]:
randint(2,10,5)

array([9, 2, 5, 7, 9])